### ISSUE TITLE
Assessment Feedback

### ISSUE THREAD

**Issue by mnhollandplum** [Josenecal/mod_0_assessment#1]
Hey Joe,

All looks good here! Congrats on making it through Mod 0! You'll be receiving feedback on your Mod 1 Prework tonight as well, but passing the Technical Assessment means you're ready to start Mod 1! Let me know if you have any questions.

**Comment by Josenecal** [comment]
Hi Nikki,

Yaaasss! Thank you so much for the good news, I'm so excited! No questions yet, I'm just looking forward to catching back up on sleep over the holidays. Thanks for all of you feedback!
